`mixed_precision` set to false
Change default value of `"mixed_precision" : false` as when it is set true it leads to  `raise RuntimeError(f" [!] NaN loss with {key}.")
RuntimeError:  [!] NaN loss with decoder_loss.`